### ISSUE TITLE
Stash加入时报错

### ISSUE THREAD

**Issue by FrankYip1020** [NSRingo/Siri#2]
Stash加入时显示格式错误
![image](https://github.com/user-attachments/assets/c49bdbfc-4d96-4a50-b7b2-f3cb7a09c333)

**Comment by VirgilClyne** [comment]
try [v4.2.6](https://github.com/NSRingo/Siri/releases/tag/v4.2.6)

**Comment by FrankYip1020** [comment]
> try [v4.2.6](https://github.com/NSRingo/Siri/releases/tag/v4.2.6)

It works.
